### PR TITLE
starting new git flow practice

### PR DESCRIPTION
**Pull request by tommartinaz**
- [x] The current reducer uses wet code with filter HOF. This needs to be updated to use reduce rather than filter.
- [x] Currently the tables have no good visual styling and don't use withStyles. Need to update the table view to use Material-UI's withStyles. The tables should look something more like this:
screen shot 2017-12-05 at 9 41 36 am

Checkbox above doesn't seem to be working

### CODE REVIEW

**Review by anthonykulis — COMMENTED** [review]
hey, where you at on starting this pr?

**Comment by tommartinaz** [comment]
@anthonykulis 
Ok, done updating code. Ready for final review.

**Comment by anthonykulis** [comment]
No. You needed the 👍  on the review before you should have started your code. Issue I have is that I dont know what "fixing the reducers" is nor do I know what "fix the tables" is. The goal here is to describe the purpose and reviewable material so another, me in this case, who has no idea what you are trying to accomplish, can go in and say evaluate the code. So please update the punch list.

Please reference https://github.com/chassi-dev/chassi-keycloak-js/pull/3

**Comment by tommartinaz** [comment]
Ah, gotcha. I just hadn't heard from you at all so wasn't sure and went ahead to fix stuff. I'll go back and edit the initial comment requesting design review. By the way, the link in your last comment is giving me a 404 error.

**Comment by anthonykulis** [comment]
hmm. ok. thats prob bc the front end collaborators isnt working well. I will grab a screen shot
screen shot 2017-12-05 at 10 30 30 am

**Review by anthonykulis — APPROVED** [review]

**Pull request merged**
